# Generated by Django 3.1.3 on 2021-01-03 12:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20201227_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='address',
            field=models.TextField(blank=True, max_length=512, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 5, 12, 22, 57, 785583, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
