# Generated by Django 3.1.3 on 2021-01-21 20:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20210103_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 20, 56, 12, 618597, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
